# Exported from:        http://MacBook-Pro.local:5516/
# Release version:      24.1.3
# Date created:         Thu Jan 16 11:28:18 EST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials
spec:
- template: sd
  scheduledStartDate: 2025-01-16T09:00:00-05:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
