# Exported from:        http://MacBook-Pro.local:5516/
# Release version:      24.1.3
# Date created:         Thu Jan 16 11:50:06 EST 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials
spec:
- template: XYZ
  scheduledStartDate: 2025-01-16T09:00:00-05:00
  dueDate: 2025-01-16T10:00:00-05:00
  phases:
  - phase: New Phase
    tasks:
    - name: "1"
      type: xlrelease.Task
    - name: cr
      type: xlrelease.CreateReleaseTask
      template: anthem-test/221175-Third
  riskProfile: Default risk profile
  author: admin
