# Exported from:        http://MacBook-Pro.local:5516/
# Release version:      24.1.3
# Date created:         Thu Jan 16 12:20:38 EST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
