# Exported from:        http://MacBook-Pro.local:5516/
# Release version:      24.1.3
# Date created:         Thu Jan 16 11:05:29 EST 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_221175-Third.yaml
  - Template_221175.yaml
  - Template_Anth-221175-second.yaml
  - Template_ERM.yaml
  - Template_argocd-test.yaml
  - Template_test2.yaml
